---@diagnostic disable: undefined-global

local GREEK =
	"(alpha|beta|gamma|delta|epsilon|zeta|eta|theta|iota|kappa|lambda|mu|nu|xi|pi|pi|rho|sigma|tau|upsilon|phi|chi|psi|omega|Gamma|Delta|Theta|Lambda|Xi|Pi|Sigma|Upsilon|Phi|Psi|Omega|varepsilon|vartheta|varpi|varrho|varsigma|varphi)"

return {}, {
	s({trig = ";a", wordTrig = false}, { t("\\alpha ") }),
	s({trig = ";b", wordTrig = false}, { t("\\beta ") }),
	s({trig = ";g", wordTrig = false}, { t("\\gamma ") }),
	s({trig = ";d", wordTrig = false}, { t("\\delta ") }),
	s({trig = ";e", wordTrig = false}, { t("\\epsilon ") }),
	s({trig = ";z", wordTrig = false}, { t("\\zeta ") }),
	s({trig = ";h", wordTrig = false}, { t("\\eta ") }),
	s({trig = "\\tau h", wordTrig = false}, { t("\\theta ") }),
	s({trig = ";i", wordTrig = false}, { t("\\iota ") }),
	s({trig = ";k", wordTrig = false}, { t("\\kappa ") }),
	s({trig = ";l", wordTrig = false}, { t("\\lambda ") }),
	s({trig = ";m", wordTrig = false}, { t("\\mu ") }),
	s({trig = ";n", wordTrig = false}, { t("\\nu ") }),
	s({trig = ";x", wordTrig = false}, { t("\\xi ") }),
	s({trig = ";p", wordTrig = false}, { t("\\pi ") }),
	s({trig = "pi", wordTrig = false}, { t("\\pi ") }),
	s({trig = ";r", wordTrig = false}, { t("\\rho ") }),
	s({trig = ";s", wordTrig = false}, { t("\\sigma ") }),
	s({trig = ";t", wordTrig = false}, { t("\\tau ") }),
	s({trig = ";u", wordTrig = false}, { t("\\upsilon ") }),
	s({trig = "\\pi h", wordTrig = false}, { t("\\phi ") }),
	s({trig = ";ch", wordTrig = false}, { t("\\chi ") }),
	s({trig = "\\pi s", wordTrig = false}, { t("\\psi ") }),
	s({trig = ";w", wordTrig = false}, { t("\\omega ") }),
	s({trig = ";G", wordTrig = false}, { t("\\Gamma ") }),
	s({trig = ";D", wordTrig = false}, { t("\\Delta ") }),
	s({trig = ";Th", wordTrig = false}, { t("\\Theta ") }),
	s({trig = ";L", wordTrig = false}, { t("\\Lambda ") }),
	s({trig = ";X", wordTrig = false}, { t("\\Xi ") }),
	s({trig = ";P", wordTrig = false}, { t("\\Pi ") }),
	s({trig = ";S", wordTrig = false}, { t("\\Sigma ") }),
	s({trig = ";U", wordTrig = false}, { t("\\Upsilon ") }),
	s({trig = "\\Pi h", wordTrig = false}, { t("\\Phi ") }),
	s({trig = "\\Pi s", wordTrig = false}, { t("\\Psi ") }),
	s({trig = ";W", wordTrig = false}, { t("\\Omega ") }),
	s({trig = ";ve", wordTrig = false}, { t("\\varepsilon ") }),
	s({trig = ";vth", wordTrig = false}, { t("\\vartheta ") }),
	s({trig = ";vp", wordTrig = false}, { t("\\varpi ") }),
	s({trig = ";vr", wordTrig = false}, { t("\\varrho ") }),
	s({trig = ";vs", wordTrig = false}, { t("\\varsigma ") }),
	s({trig = ";vph", wordTrig = false}, { t("\\varphi ") }),
}
