---@diagnostic disable: undefined-global

return {}, {
	s(";a", { t("\\alpha") }),
	s(";b", { t("\\beta") }),
	s(";g", { t("\\gamma") }),
	s(";d", { t("\\delta") }),
	s(";e", { t("\\epsilon") }),
	s(";z", { t("\\zeta") }),
	s(";h", { t("\\eta") }),
	s(";th", { t("\\theta") }),
	s(";i", { t("\\iota") }),
	s(";k", { t("\\kappa") }),
	s(";l", { t("\\lambda") }),
	s(";m", { t("\\mu") }),
	s(";n", { t("\\nu") }),
	s(";x", { t("\\xi") }),
	s(";pi", { t("\\pi") }),
	s("pi", { t("\\pi") }),
	s(";r", { t("\\rho") }),
	s(";s", { t("\\sigma") }),
	s(";ta", { t("\\tau") }),
	s(";u", { t("\\upsilon") }),
	s(";ph", { t("\\phi") }),
	s(";ch", { t("\\chi") }),
	s(";ps", { t("\\psi") }),
	s(";w", { t("\\omega") }),
	s(";G", { t("\\Gamma") }),
	s(";D", { t("\\Delta") }),
	s(";Th", { t("\\Theta") }),
	s(";L", { t("\\Lambda") }),
	s(";X", { t("\\Xi") }),
	s(";P", { t("\\Pi") }),
	s(";S", { t("\\Sigma") }),
	s(";U", { t("\\Upsilon") }),
	s(";Ph", { t("\\Phi") }),
	s(";Ps", { t("\\Psi") }),
	s(";W", { t("\\Omega") }),
	s(";ve", { t("\\varepsilon") }),
	s(";vth", { t("\\vartheta") }),
	s(";vp", { t("\\varpi") }),
	s(";vr", { t("\\varrho") }),
	s(";vs", { t("\\varsigma") }),
	s(";vph", { t("\\varphi") }),
}
